// WARNING: THIS CODE WAS AUTOMATICALLY GENERATED BY THE API GENERATOR. DO NOT
// EDIT THIS FILE. TO ADD MORE FUNCTIONALITY TO THIS PACKAGE, CREATE NEW FILES
// IN THE SAME DIRECTORY.
package model

import (
	"context"
	"errors"
	"strings"
)

type myservice interface {

	// sign up
	SignUp(ctx context.Context, input SignupInput) (
		output SignupOutput,
		err error,
	)
}

// SignupInput:
type SignupInput struct {

	// Password:
	Password string `json:"password"`

	// Username:
	Username string `json:"username"`
}

// Validate sanitizes and validates SignupInput
// nolint: dupl
func (input *SignupInput) Validate() error {

	// trim heading and trailing whitespace from Password
	input.Password = strings.TrimSpace(input.Password)

	if input.Password == "" {
		return errors.New("password must be provided")
	}

	// trim heading and trailing whitespace from Username
	input.Username = strings.TrimSpace(input.Username)

	if input.Username == "" {
		return errors.New("username must be provided")
	}

	return nil
}

// SignupOutput:
type SignupOutput struct {

	// Message:
	Message string `json:"message"`
}

// Validate sanitizes and validates SignupOutput
// nolint: dupl
func (input *SignupOutput) Validate() error {

	// trim heading and trailing whitespace from Message
	input.Message = strings.TrimSpace(input.Message)

	if input.Message == "" {
		return errors.New("message must be provided")
	}

	return nil
}
